### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sdgandhi** [Syntertainment/SYNUtils#3]
- [x] Array+Utils
- [x] CGPoint+Utils
- [x] CGRect+Utils
- [x] CGSize+Utils
- [x] Dictionary+Utils
- [x] Double+Utils
- [x] NSData+Utils
- [x] NSDate+Utils
- [x] NSObject+Utils
- [x] NSRegularExpression+Utils
- [x] NSString+Utils
- [x] NSTimer+Utils
- [x] Range+Utils
- [x] UIColor+Utils
- [x] UIImage+Utils
- [x] Math
- [x] Threading
- [x] Compile into Markdown for README.md

**Comment by jhurliman** [comment]
At first I thought these were all pull requests and I got so excited! Ah well...

My preferred documentation format is Markdown in the README.md, with formatting similar to the docs for https://github.com/caolan/async (start at the Documentation section). This is probably the most important task, since the utility of a system framework extending library like this is directly tied to the documentation quality.

**Comment by sdgandhi** [comment]
@jhurliman The readme looks good to me! Still needs example code blocks, but I can make a separate issue for that, or we can remove those altogether since it's pretty obvious from the docs.

**Comment by jhurliman** [comment]
Library has been updated with code examples in the inline docs. I just need to update the generateDocs script to parse them and spit out proper Markdown.

**Comment by jhurliman** [comment]
Examples included in docs and docs generator improved to strip out empty sections.
